### ISSUE TITLE
App crashing in ios7

### ISSUE THREAD

**Issue by chandramouli952** [Worldpay/worldpay-lib-ios#1]
Hello,
          library is working fine in iOS 8 but it is not working in iOS 7.I am getting EXC_ARM_BREAKPOINT error and the app is terminating please let me know is there any issue in my side or in the library 

Regards,

**Comment by dcapilla** [comment]
Hello,
You were right, it seemed to be a problem with the library on iOS7. The code was trying to load a font that didn’t exist and iOS7 was resulting in a crash (iOS8 was working fine as you pointed out). We’ve fixed it (commit e92e19b2c976903da07072438ff82813662a0d1e) so it should be working now. Please let us know.

Regards,
