### ISSUE TITLE
App is still crashing in ios 7 

### ISSUE THREAD

**Issue by chandramouli952** [Worldpay/worldpay-lib-ios#2]
Application is still crashing in this method 
- (void)loadFont:(NSString *)fontName {
  NSString *fontPath = [[WorldpayUtils frameworkBundle] pathForResource:fontName ofType:@"ttf"];
  please let me if I am making any mistake in using the library

**Comment by ao** [comment]
We no-longer call this method, can you please git pull this repo again and rebuild.
You can test this by downloading and running the sample project from scratch.

Can you please indicate where you are calling this method from?
