### ISSUE TITLE
Could not find setClientKey:YOUR_CLIENT_KEY in Swift ?

### ISSUE THREAD

**Issue by speaktoalvin** [Worldpay/worldpay-lib-ios#3]
I am trying to integrate World Pay iOS SDK with Swift 2.0 and iOS 9.2. As per the documentation there should be a function called "setClientKey". Unfortunately i could not find any functions like that.

```
            [ [Worldpay sharedInstance] setClientKey:YOUR_CLIENT_KEY ];
```

When i type this Xcode helps with auto-completion, but i could see only these.

```
    Worldpay.sharedInstance().setClass(AnyClass?, forClassName: String)
    Worldpay.sharedInstance().setClassName(String?, forClass: AnyClass)
```

I found an another on using swift.  This returns an error like this "Cannot assign to property: function call returns immutable value"

```
            Worldpay.sharedInstance().clientKey = ""
```

But inside World Pay iOS Library, i saw this.

 "Property that sets the Client Key which is used for API calls made directly from your customer's browser"
@property (nonatomic, retain) NSString *clientKey;

Which means that i can set Client Key using this property. But i could not. 

Is there any workaround ? Let me know please.

**Comment by donaldking** [comment]
Hi, I'm getting 401 when calling https://qa02-api.worldpay.io/v1/tokens to create token. My client key is set correctly.

**Comment by speaktoalvin** [comment]
You please try to integrate World Pay in a Swift project. Import the header in bridging-header and try to call this method "setClientKey". Please let me know whether you can see any methods like that or not.

**Comment by ao** [comment]
@donaldking We have identified the problem and will release an updated version tomorrow.

@alvinvarghese The library was written for Objective C, we are in the process of adding Swift support for it. Will let you know once this is ready.

**Comment by speaktoalvin** [comment]
@ao That's great. Looking forward to it :)

**Comment by ao** [comment]
@donaldking please pull the repo.

**Comment by donaldking** [comment]
@ao Thanks! that was a quick fix! :)

**Comment by donaldking** [comment]
@alvinvarghese You can surely set client key in a swift project. It works perfectly fine and there are many ways you could do this. The way i've implemented it is by simply subclassing WorldPay and calling self.clientKey = "my-client-key" in my swift project. Works perfectly fine. @ao ObjC proj / lib would work PERFECTLY well with Swift projects :) I have lots! @alvinvarghese see my screen shot attached. Let me know if you have any issues. Cheers
![screen shot 2016-01-22 at 02 47 59](https://cloud.githubusercontent.com/assets/4445659/12501206/a2bf9fd0-c0b2-11e5-971b-592906a8321f.png)

**Comment by speaktoalvin** [comment]
Ohh great. I didn't think about that.

**Comment by ao** [comment]
Version 1.3.0 has just been released. This should resolve your Swift issues.

**Comment by speaktoalvin** [comment]
Thats really great :)
