### ISSUE TITLE
Create Token API returning 401

### ISSUE THREAD

**Issue by donaldking** [Worldpay/worldpay-lib-ios#4]
Hi, I'm getting 401 when calling https://qa02-api.worldpay.io/v1/tokens to create token. My client key is set correctly. Error response:

failure info:  [message: EXT_519: Unauthorized Access, customCode: UNAUTHORIZED, errorHelpUrl: <null>, description: Request can't be authorized, please validate your request, httpStatusCode: 401, originalRequest: {'clientKey':'T_C_de573437-7f54-44fa-b0e5-064a761775e4','reusable':true,'paymentMethod':{'cardNumber':'***\* ***\* ***\* 1111','cvc':'*_**','expiryMonth':'__','type':'Card','name':'Donald King','expiryYear':'_***'}}] [Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: unauthorized (401)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x7fef6056fd90> { URL: https://qa02-api.worldpay.io/v1/tokens } { status code: 401, headers {
    Connection = "keep-alive";
    "Content-Length" = 418;
    "Content-Type" = "application/json;charset=UTF-8";
    Date = "Wed, 20 Jan 2016 11:46:13 GMT";
    Server = "Windows NT 3.x";
    "X-Content-Type-Options" = nosniff;
} }, NSErrorFailingURLKey=https://qa02-api.worldpay.io/v1/tokens, com.alamofire.serialization.response.error.data=<7b226874 74705374 61747573 436f6465 223a3430 312c2263 7573746f 6d436f64 65223a22 554e4155 54484f52 495a4544 222c226d 65737361 6765223a 22455854 5f353139 3a20556e 61757468 6f72697a 65642041 63636573 73222c22 64657363 72697074 696f6e22 3a225265 71756573 74206361 6e277420 62652061 7574686f 72697a65 642c2070 6c656173 65207661 6c696461 74652079 6f757220 72657175 65737422 2c226572 726f7248 656c7055 726c223a 6e756c6c 2c226f72 6967696e 616c5265 71756573 74223a22 7b27636c 69656e74 4b657927 3a27545f 435f6465 35373334 33372d37 6635342d 34346661 2d623065 352d3036 34613736 31373735 6534272c 27726575 7361626c 65273a74 7275652c 27706179 6d656e74 4d657468 6f64273a 7b276361 72644e75 6d626572 273a272a 2a2a2a20 2a2a2a2a 202a2a2a 2a203131 3131272c 27637663 273a272a 2a2a2a27 2c276578 70697279 4d6f6e74 68273a27 2a2a272c 27747970 65273a27 43617264 272c276e 616d6527 3a27446f 6e616c64 204b696e 67272c27 65787069 72795965 6172273a 272a2a2a 2a277d7d 227d>, NSLocalizedDescription=Request failed: unauthorized (401)}]

**Comment by ao** [comment]
We have identified the problem and will release an updated version tomorrow.

**Comment by ao** [comment]
This has been resolved, please pull the repo.

**Comment by MeghaUgile** [comment]
can you please share, how you have resolved this issue?

**Comment by MeghaUgile** [comment]
Still i am facing same issue

**Comment by vikas583** [comment]
can you please tell @donaldking if your issue was resolved or not, because i am facing the same issue.

**Comment by AmmarOfficewalaSerpentCS** [comment]
@ao 
Can you please told this issue fix or not 
still, I am facing this issue
