### ISSUE TITLE
Stuck at integrating worldpay

### ISSUE THREAD

**Issue by Salmancs43** [Worldpay/worldpay-lib-ios#9]
I used the 'AFNetworking', '~> 3.0’ in my whole app and now at the end i want to integerate the worldpay payment method but when i import the worldpay file i got this error

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AFHTTPRequestOperation", referenced from:
      objc-class-ref in libWorldpay.a(Worldpay.o)
      objc-class-ref in libWorldpay.a(ThreeDSController.o)
      objc-class-ref in libWorldpay.a(APMController.o)
  "_OBJC_CLASS_$_AFHTTPRequestOperationManager", referenced from:
      objc-class-ref in libWorldpay.a(WorldpayUtils.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I google it and try everything but nothing worked. Please tell me the solution. Thanks

**Comment by aaronwardle** [comment]
It's perhaps a late reply but my advice would be don't bother with WorldPay and the iOS SDK we reported a huge fraud issue months ago and are still waiting for a solution, and every day fraudsters are using our mobile app to test stolen credit cards. 

With the SDK currently and even the sample project 3DS does not work so the level of fraud transactions are very high. 

It's a shame but we are now looking to switch to JudoPay or Stripe.

**Comment by Salmancs43** [comment]
Thanks for your comment.
